[package]
name = "PongEnhanced"
version = "0.1.0"
edition = "2024"

[dependencies]
bevy = { version = "0.17.3" , features = [
    "default",
    "bevy_dev_tools",
    "experimental_bevy_ui_widgets",
    "bevy_ui"
]}
avian2d = "0.4.1"
leafwing-input-manager = "0.19.0"
derive_more = "2.1.1"
erased-serde = "0.4.9"
bevy_tween = "0.11.0"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.149"

[target.'cfg(windows)'.dependencies]
windows = { version = "0.62.2", features = ["Win32_Graphics_Gdi"] }