[package]
name = "PongEnhanced"
version = "0.1.0"
edition = "2024"

[dependencies]
bevy = { version = "0.16.1", features = ["bevy_dev_tools", "default"] }
bevy_rapier2d = "0.31.0"
leafwing-input-manager = "0.17.1"