[package]
name = "PongEnhanced"
version = "0.1.0"
edition = "2024"

[dependencies]
bevy = { version = "0.17.3" , features = ["default", "bevy_dev_tools"]}
avian2d = "0.4.1"
leafwing-input-manager = "0.19.0"